### ISSUE TITLE
Only one variable can be used in heading, vars etc.

### ISSUE THREAD

**Issue by crocodele** [antlau/tinycar#3]
It would be nice to be able to use multiple variables in a single value in the app manifest.

Example 1:
```
<view name="edit" data="$url.id">
    <layout>fieldlist</layout>
    <heading>$data.firstname $data.lastname</heading>
```

Example 2:
```
<dialog name="remove" data="$url.id">
    <heading>$locale.dialog_confirm</heading>
    <component type="TextContent">
        <var name="name">$model.firstname $model.lastname</var>
        <text>Hey, hey, are you completely sure you want to remove $name from the database?</text>
    </component>
```

**Comment by antlau** [comment]
That seems like a good idea and a probably a common use case... Thanks for suggesting.

The issue right now is that the variable evaluation might not yield just a string, but another datatype or even a class instance containing additional data for the component. This is particularly true with $model references.

The variable processing is however quite centralized and changing it takes effect everywhere. Also the complex types are only needed in few cases, like with <data>. So this is totally doable, there just needs to be some extra care that single variables maintain their data types while strings consisting of multiple variables should be converted into strings...

I think some refactoring needs to happen first to make this more reliable and extendable to other additional features, e.g. formatting rules for variables.

**Comment by antlau** [comment]
Note that example 2 will now work only if $model references are replaced with $data, as the first one contains model property instances and the latter the actual values.

**Comment by crocodele** [comment]
Sweet! :tada:
